version: "3.3"
services:
  tempo:
    image: lamaldiciondemandos/tempo-demo:v1

    ports:
      - "8080:8080"
    container_name: tempo
    links:
      - redis-server
      - db
    depends_on:
      - db
      - redis-server
    environment:
      PROFILE: dev
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/db_username'
      SPRING_DATASOURCE_USERNAME: db_username
      SPRING_DATASOURCE_PASSWORD: db_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - tempo_net
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_username
      POSTGRES_PASSWORD: db_password
    networks:
      - tempo_net

  redis-server:
    image: 'redis:latest'
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - tempo_net
networks:
  tempo_net:
    external: false