spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    datasource:
      url: jdbc:h2:file:./data.sql
      driver: org.h2.Driver
      username: sa
      initialization-mode: never
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    ROOT: DEBUG
    com.riu: DEBUG
    web: DEBUG
    org.hibernate.SQL : DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder : DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG

app.cache.ttl: 1800 #Cache by 30 minutes
