spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      driver-class-name: org.postgresql.Driver
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      initialization-mode: update
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data.redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  autoconfigure.exclude: "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration"

logging:
  level:
    ROOT: DEBUG
    com.riu: DEBUG
    web: DEBUG
    org.hibernate.SQL : DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder : DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG

app:
  cache.ttl: 1800 #Cache by 30 minutes
  quote: 3